// Code generated by "stringer -type=ElementType goexec.go"; DO NOT EDIT.

package goexec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[FunctionType-1]
	_ = x[ImportType-2]
	_ = x[VarType-3]
	_ = x[ConstType-4]
}

const _ElementType_name = "InvalidFunctionTypeImportTypeVarTypeConstType"

var _ElementType_index = [...]uint8{0, 7, 19, 29, 36, 45}

func (i ElementType) String() string {
	if i < 0 || i >= ElementType(len(_ElementType_index)-1) {
		return "ElementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ElementType_name[_ElementType_index[i]:_ElementType_index[i+1]]
}
