#!/bin/bash
set -eu

GO_VERSION=1.24.3

curl -sfL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz | tar -xz

export PATH=$PATH:$HOME/go/bin

go version

go install

go install golang.org/x/tools/cmd/goimports@latest
go install golang.org/x/tools/gopls@latest

gonb --install
